Repository OCA/mail, pull requests merged in 2025-07, with the labels that each got.

#58 [18.0] mail_tracking: Apply read restrictions to everyone not being superuser
  mail_tracking/models/mail_tracking_email.py
Labels: approved, bot is merging ⏳

#67 [18.0][MOV] mail_suggested_recipient_unchecked: Repository moved
  mail_suggested_recipient_unchecked/README.rst
  mail_suggested_recipient_unchecked/__init__.py
  mail_suggested_recipient_unchecked/__manifest__.py
  mail_suggested_recipient_unchecked/i18n/it.po
  mail_suggested_recipient_unchecked/i18n/mail_suggested_recipient_unchecked.pot
  mail_suggested_recipient_unchecked/models/__init__.py
  mail_suggested_recipient_unchecked/models/mail_thread.py
  mail_suggested_recipient_unchecked/pyproject.toml
  mail_suggested_recipient_unchecked/readme/CONTRIBUTORS.md
  mail_suggested_recipient_unchecked/readme/DESCRIPTION.md
  mail_suggested_recipient_unchecked/readme/USAGE.md
  mail_suggested_recipient_unchecked/static/description/icon.png
  mail_suggested_recipient_unchecked/static/description/index.html
  mail_suggested_recipient_unchecked/tests/__init__.py
  mail_suggested_recipient_unchecked/tests/test_mail_suggested_recipient_unchecked.py
Labels: bot is merging ⏳

#64 [18.0] [ADD] mail_extra_header
  mail_extra_header/README.rst
  mail_extra_header/__init__.py
  mail_extra_header/__manifest__.py
  mail_extra_header/models/__init__.py
  mail_extra_header/models/ir_mail_server.py
  mail_extra_header/pyproject.toml
  mail_extra_header/readme/CONFIGURE.md
  mail_extra_header/readme/CONTRIBUTORS.md
  mail_extra_header/readme/DESCRIPTION.md
  mail_extra_header/static/description/index.html
  mail_extra_header/tests/__init__.py
  mail_extra_header/tests/test_mail_extra_header.py
  mail_extra_header/views/ir_mail_server.xml
Labels: approved, ready to merge, bot is merging ⏳

#70 [18.0][FIX] mail_composer_cc_bcc: Support placeholders
  mail_composer_cc_bcc/README.rst
  mail_composer_cc_bcc/readme/CONTRIBUTORS.md
  mail_composer_cc_bcc/static/description/index.html
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mail_composer_cc_bcc/wizards/mail_compose_message.py
Labels: approved, bot is merging ⏳
