Repository OCA/mail, pull requests merged in 2025-02, with the labels that each got.

#32 [18.0][FIX] mail_debrand: ensure footer is rendered in test
  mail_debrand/tests/test_mail_debrand.py
Labels: bot is merging ⏳

#20 [18.0][MIG] mail_outbound_static
  mail_outbound_static/README.rst
  mail_outbound_static/__init__.py
  mail_outbound_static/__manifest__.py
  mail_outbound_static/i18n/es.po
  mail_outbound_static/i18n/it.po
  mail_outbound_static/i18n/mail_outbound_static.pot
  mail_outbound_static/models/__init__.py
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/pyproject.toml
  mail_outbound_static/readme/CONTRIBUTORS.md
  mail_outbound_static/readme/DESCRIPTION.md
  mail_outbound_static/readme/ROADMAP.md
  mail_outbound_static/readme/USAGE.md
  mail_outbound_static/static/description/icon.png
  mail_outbound_static/static/description/index.html
  mail_outbound_static/tests/__init__.py
  mail_outbound_static/tests/test.msg
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_outbound_static/views/ir_mail_server_view.xml
Labels: approved, bot is merging ⏳

#21 [18.0][MIG] mail_partner_forwarding: Migration to 18.0
  mail_partner_forwarding/README.rst
  mail_partner_forwarding/__init__.py
  mail_partner_forwarding/__manifest__.py
  mail_partner_forwarding/i18n/es.po
  mail_partner_forwarding/i18n/it.po
  mail_partner_forwarding/i18n/mail_partner_forwarding.pot
  mail_partner_forwarding/models/__init__.py
  mail_partner_forwarding/models/mail_thread.py
  mail_partner_forwarding/models/res_partner.py
  mail_partner_forwarding/models/res_user.py
  mail_partner_forwarding/pyproject.toml
  mail_partner_forwarding/readme/CONTRIBUTORS.md
  mail_partner_forwarding/readme/DESCRIPTION.md
  mail_partner_forwarding/readme/HISTORY.md
  mail_partner_forwarding/readme/USAGE.md
  mail_partner_forwarding/static/description/icon.png
  mail_partner_forwarding/static/description/index.html
  mail_partner_forwarding/tests/__init__.py
  mail_partner_forwarding/tests/models/__init__.py
  mail_partner_forwarding/tests/models/fake_order.py
  mail_partner_forwarding/tests/test_mail_forwarding.py
  mail_partner_forwarding/views/res_partner_views.xml
  mail_partner_forwarding/views/res_user_views.xml
  test-requirements.txt
Labels: approved, ready to merge, merged 🎉
